import React, { useMemo, useState } from "react";
import Modal from "../components/Modal";
import AnalyticsHeader from "../components/AnalyticsHeader";
import { customerData } from "../data/sampleData";
import DataRequired from "../components/DataRequired";

function Customers({ analysis, onAddData }) {
  const [selected, setSelected] = useState(null);
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => customerData.filter((row) => row.name.toLowerCase().includes(query.toLowerCase()) || row.segment.toLowerCase().includes(query.toLowerCase())), [query]);
  const totalSpend = customerData.reduce((sum, row) => sum + row.totalSpend, 0);
  if (!analysis) return <DataRequired eyebrow="CUSTOMER INTELLIGENCE" title="Customer portfolio" subtitle="Understand your highest-value relationships and segments." onAddData={onAddData} />;
  return <div className="analytics-page"><AnalyticsHeader eyebrow="CUSTOMER INTELLIGENCE" title="Customer portfolio" subtitle="Understand your highest-value relationships and segments." actionLabel="Export customers" onAction={() => window.print()} onSecondary={() => setQuery("")} /><div className="insight-stat-grid"><div className="insight-stat blue"><span>Active customers</span><strong>{customerData.length}</strong><small className="stat-positive">↑ 12% this month</small></div><div className="insight-stat purple"><span>Total customer value</span><strong>₹{totalSpend.toLocaleString()}</strong><small>Across tracked accounts</small></div><div className="insight-stat orange"><span>Wholesale share</span><strong>67%</strong><small>Of total portfolio value</small></div><div className="insight-stat green"><span>Retention signal</span><strong>Strong</strong><small className="stat-positive">Healthy account activity</small></div></div><div className="customer-highlight"><div className="highlight-copy"><span className="source-kicker">HIGH-VALUE ACCOUNT</span><h2>Patel Industries</h2><p>Your highest-value wholesale relationship is contributing ₹5,80,000 in total spend.</p><button className="highlight-button" onClick={() => setSelected(customerData[1])}>View account →</button></div><div className="highlight-figure"><strong>₹5.8L</strong><span>Total spend</span><div className="figure-bars"><i></i><i></i><i></i><i></i><i></i></div></div></div><section className="analytics-panel table-panel"><div className="table-toolbar"><div><h2>Customer directory</h2><p>Click any account to open its relationship summary</p></div><label className="table-search">⌕<input placeholder="Search customers or segments" value={query} onChange={(event) => setQuery(event.target.value)} /></label></div><div className="data-table-wrap"><table className="pro-table"><thead><tr><th>Customer</th><th>Segment</th><th>Total orders</th><th>Total spend</th><th>Relationship</th><th></th></tr></thead><tbody>{filtered.map((row) => <tr key={row.id} onClick={() => setSelected(row)}><td><strong>{row.name}</strong><small>Account #{String(row.id).padStart(4, "0")}</small></td><td><span className={`table-status ${row.segment === "Wholesale" ? "purple-status" : "blue-status"}`}>{row.segment}</span></td><td>{row.totalOrders || "—"}</td><td><strong>₹{row.totalSpend.toLocaleString()}</strong></td><td><span className="table-status positive-status">Active</span></td><td className="row-arrow">→</td></tr>)}</tbody></table></div></section><Modal isOpen={!!selected} onClose={() => setSelected(null)} title={selected ? `${selected.name} — Customer detail` : "Customer detail"}>{selected && <div className="detail-list"><div><span>Segment</span><strong>{selected.segment}</strong></div><div><span>Total spend</span><strong>₹{selected.totalSpend.toLocaleString()}</strong></div><div><span>Relationship status</span><strong>Active account</strong></div></div>}</Modal></div>;
}

export default Customers;
